LOG_FILE_NAME = "log"
GAME_WINDOW_NAME = "WoT Client"

VERIFIED_CHARRECOG_PATH = "verified"
UNVERIFIED_CHARRECOG_PATH = "unverified"

GAME_RECT_LEFT = 521
GAME_RECT_TOP = 42
GAME_RECT_WIDTH = 2476
GAME_RECT_HEIGHT = 1288

GAME_MAP_NAME_LEFT = 1000
GAME_MAP_NAME_TOP = 64
GAME_MAP_NAME_WIDTH = 180
GAME_MAP_NAME_HEIGHT = 64

# GAME_ENEMY_NAME_LEFT = 2340
# GAME_ENEMY_NAME_TOP = 96
# GAME_ENEMY_NAME_WIDTH = 82
# GAME_ENEMY_NAME_HEIGHT = 25
GAME_ENEMY_NAME_LEFT = 1426
GAME_ENEMY_NAME_TOP = 491
GAME_ENEMY_NAME_WIDTH = 74
GAME_ENEMY_NAME_HEIGHT = 25